repository: johsuan/johsuan.github.io
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://johsuan.github.io" # the base hostname & protocol for your site, e.g. http://example.com


# Build settings
markdown: kramdown
permalink: pretty
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll/tagging

paginate: 5
paginate_path: "/page/:num"


# Pages Path
defaults:
  - scope:
      path: '_pages'
    values:
      permalink: /:basename:output_ext

include:
  - _pages

# Projects Path
defaults:
  - scope:
      path: '_projects'
    values:
      permalink: /projects/:path/
      
include:
  - _projects
# Tags
tag_page_dir:         tag
tag_page_layout:      tag_page
tag_permalink_style:  pretty

sass:
  sass_dir: _sass
  style: compressed